export type UserRole = 'superadmin' | 'admin' | 'viewer'

export type PaymentMethod =
  | 'transferencia'
  | 'stripe'
  | 'cheque'
  | 'transferencia_o_cheque'
  | 'efectivo'
  | 'no_paga'
  | 'otro'

export type BillingType = 'monthly' | 'no_charge' | 'special'

export type InvoiceStatus = 'pending' | 'partial' | 'paid' | 'overdue' | 'waived' | 'cancelled'

export interface User {
  _id: string
  name: string
  email: string
  role: UserRole
  isActive: boolean
  photoUrl?: string
  lastLoginAt?: string
  receivesNotifications: boolean
  createdAt: string
  updatedAt: string
}

export interface ClientSplit {
  label?: string
  amount: number
  day?: number | null
}

export type ArchiveReason =
  | 'impago'
  | 'cancelacion_cliente'
  | 'cierre_negocio'
  | 'competencia'
  | 'precio'
  | 'insatisfaccion_resultados'
  | 'pausa_temporal'
  | 'fin_contrato'
  | 'decision_bakano'
  | 'otro'

export const ARCHIVE_REASON_LABELS: Record<ArchiveReason, string> = {
  impago: 'Impago / mora',
  cancelacion_cliente: 'El cliente canceló el servicio',
  cierre_negocio: 'Cerró el negocio',
  competencia: 'Se fue con la competencia',
  precio: 'Precio',
  insatisfaccion_resultados: 'Insatisfecho con los resultados',
  pausa_temporal: 'Pausa temporal',
  fin_contrato: 'Fin de contrato',
  decision_bakano: 'Decisión de Bakano',
  otro: 'Otro',
}

export interface ClientAttachment {
  name: string
  url: string
  publicId?: string
  mimeType?: string
  size?: number
  uploadedAt: string
}

export interface ClientLifecycleEntry {
  action: 'archived' | 'reactivated'
  reason?: ArchiveReason
  notes?: string
  attachments: ClientAttachment[]
  durationDays?: number
  revenueToDate?: number
  at: string
  byName?: string
}

export interface InvoiceDeferral {
  previousDueDate: string
  newDueDate: string
  reason?: string
  notes?: string
  agreedAt: string
  agreedByName?: string
}

export interface ChurnReasonRow {
  reason: ArchiveReason
  label: string
  count: number
  lostMonthlyAmount: number
  avgLifetimeDays: number
  totalLifetimeRevenue: number
}

export interface ChurnReport {
  byReason: ChurnReasonRow[]
  totals: {
    archivedClients: number
    lostMonthlyAmount: number
    avgLifetimeDays: number
    totalLifetimeRevenue: number
  }
  recent: Array<{
    _id: string
    name: string
    archivedAt: string
    reason: ArchiveReason
    label: string
    lifetimeDays: number
    lifetimeRevenue: number
    amount: number
    attachmentsCount: number
  }>
}

export interface Client {
  _id: string
  name: string
  legalName?: string
  contactName?: string
  contactEmail?: string
  contactPhone?: string
  amount: number
  currency: string
  issueDay?: number | null
  collectionDay?: number | null
  collectionDayLabel?: string
  paymentMethod: PaymentMethod
  billingType: BillingType
  splits: ClientSplit[]
  notes?: string
  tags: string[]
  workspaceId?: string | null
  workspaceName?: string | null
  workspaceLinkedAt?: string | null
  /** Imagen del espacio cacheada desde métricas. Úsala como avatar del cliente. */
  workspaceImageUrl?: string | null
  accessOverride?: AccessOverride | null
  shouldBeClosed?: boolean
  overdueAmount?: number
  maxDaysOverdue?: number
  autoDeactivate: boolean
  graceDays?: number | null
  isActive: boolean
  workspaceIsActive?: boolean | null
  deactivatedAt?: string | null
  deactivationReason?: string
  startDate: string
  endDate?: string | null
  /** Primer período "YYYY-MM" a facturar. Para servicios que arrancan más adelante. */
  billingStartPeriod?: string | null

  isArchived: boolean
  archivedAt?: string | null
  archiveReason?: ArchiveReason | null
  archiveNotes?: string
  archiveAttachments: ClientAttachment[]
  lifetimeDays?: number | null
  lifetimeRevenue?: number | null
  lifecycleHistory: ClientLifecycleEntry[]

  stripeCustomerId?: string | null
  createdAt: string
  updatedAt: string
}

export interface Invoice {
  _id: string
  clientId: string | Client
  clientName: string
  period: string
  splitIndex: number
  splitLabel?: string
  amount: number
  currency: string
  paidAmount: number
  issueDate?: string | null
  dueDate: string
  originalDueDate?: string | null
  deferrals: InvoiceDeferral[]
  isAdvance: boolean
  paidAt?: string | null
  status: InvoiceStatus
  notes?: string
  autoGenerated: boolean
  reminderSentAt?: string | null
  overdueNotifiedAt?: string | null
  deactivation: {
    warnedAt?: string | null
    deactivatedAt?: string | null
    reactivatedAt?: string | null
    reason?: string
  }
  workspaceId?: string | null
  createdAt: string
  updatedAt: string
}

export interface Payment {
  _id: string
  invoiceId: string | Invoice
  clientId: string | Client
  clientName: string
  period: string
  amount: number
  currency: string
  paidAt: string
  method: PaymentMethod
  reference?: string
  notes?: string
  receiptUrl?: string
  registeredByName?: string
  createdAt: string
}

export interface WorkspaceImage {
  name: string
  url: string
  categoria: string
  tipo?: string
}

export interface Workspace {
  _id: string
  name: string
  isActive: boolean
  adminName?: string
  adminEmail?: string
  adminPhotoUrl?: string | null
  createdAt?: string

  /** Imagen principal del espacio: logo del cliente o foto de su página de Meta. */
  imageUrl?: string | null
  logoUrl?: string | null
  pictureUrl?: string | null
  images?: WorkspaceImage[]
  pageName?: string | null
  instagramAccountName?: string | null
  tipoNegocio?: string | null
  vertical?: string | null

  client?: Pick<Client, '_id' | 'name' | 'amount' | 'isActive'> | null
  /** El espacio está abierto pero el cliente lleva mora por encima de sus días de gracia. */
  shouldBeClosed?: boolean
  overdueAmount?: number
  maxDaysOverdue?: number
  accessOverride?: AccessOverride | null
}

/** Acceso abierto a propósito pese a la mora. */
export interface AccessOverride {
  enabled: boolean
  reason?: string
  grantedAt?: string | null
  grantedByName?: string
  /** null = indefinida, hay que revocarla a mano. */
  until?: string | null
  revokedAt?: string | null
  revokedByName?: string
}

export interface NotificationSettings {
  _id?: string
  fromEmail: string
  replyTo: string
  recipients: string[]
  alwaysTo: string[]
  ccEmails: string[]
  toggles: {
    paymentRegistered: boolean
    reminderBefore: boolean
    overdue: boolean
    deactivation: boolean
    monthlySummary: boolean
  }
  reminderDaysBefore: number
  graceDays: number
  warnBeforeDeactivationDays: number
  autoDeactivateEnabled: boolean
  sendHour: number
}

export interface AppSettings {
  _id?: string
  appName: string
  logoUrl: string
  iconUrl: string
  brandColors: Record<string, string>
  currency: string
  timezone: string
}

export interface DashboardSummary {
  period: string
  expectedAmount: number
  collectedAmount: number
  pendingAmount: number
  overdueAmount: number
  collectionRate: number
  clientsTotal: number
  clientsActive: number
  clientsOverdue: number
  invoicesTotal: number
  invoicesPaid: number
  invoicesPending: number
  invoicesOverdue: number
  workspacesDeactivated: number
  /** Lo que debería entrar cada mes si todos los clientes activos pagan. */
  idealMonthlyAmount: number
  archivedClients: number
}

export interface RevenuePoint {
  period: string
  label: string
  expected: number
  collected: number
}

export interface BreakdownItem {
  key: string
  label: string
  count: number
  amount: number
}

export interface AgingBucket {
  bucket: string
  count: number
  amount: number
}

export interface ClientStats {
  totalClients: number
  activeClients: number
  inactiveClients: number
  archivedClients: number
  linkedWorkspaces: number
  expectedMonthlyAmount: number
  /** Lo que debería entrar cada mes si todos los clientes activos pagan. */
  idealMonthlyAmount: number
}

export interface InvoiceSummary {
  period: string
  total: number
  paid: number
  pending: number
  overdue: number
  waived: number
  cancelled: number
  collectedAmount: number
  expectedAmount: number
  pendingAmount: number
  collectionRate: number
}

export interface WorkspaceSuggestion {
  workspaceId: string
  workspaceName: string
  isActive: boolean
  adminName?: string
  adminEmail?: string
  imageUrl?: string | null
  score: number
}

export interface PaginatedResult<T> {
  items: T[]
  total: number
  page: number
  limit: number
  pages: number
}

export interface ToastItem {
  id: string
  type: 'success' | 'error' | 'warning' | 'info'
  title: string
  message?: string
  duration: number
}

export interface SelectOption {
  value: string | number | null
  label: string
  icon?: string
  color?: string
  description?: string
  disabled?: boolean
}
